version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run dev
      - npm run build
artifacts:
   files:
     - index.html
     - favicon.ico
     - styles/main.css
     - images/*
     - dist/bundle.js
